### ISSUE TITLE
Is there any chance running this pipeline totally without 'REFGTF'?

### ISSUE THREAD

**Issue by buhanfeng** [fw262/TAR-scRNA-seq#17]
Hi all, 

I'm dealing with a strange species which has no gtf at all. Is there any chance running this pipeline totally without 'REFGTF'?

**Comment by fw262** [comment]
Hello,

The pipeline does not explicitly perform the analysis without a reference GTF file. 

Fortunately, there is a file created called "TAR_reads.bed.gz" in rule "rule calcHMMbed" of the Snakefile which contains all the peaks in your dataset. You can actually use the regions defined in "TAR_reads.bed.gz" file as your annotations or genome reference. You can easily convert this bedfile to a .gtf or .refFlat format (refer to convertRefFlatToGTF.R script for help) for downstream analysis.

Best,
Michael

**Comment by buhanfeng** [comment]
Hi Michael,

Your advice is very helpful, I use a dummy gtf file to run the pipeline, and obtain TAR_reads.bed.gz .

Thanks for your help.
